@startuml
title Bronze challenge\nsequence diagram
participant Buggy as b #4f4
participant Station as s #44f
note over b, s #fff: Buggy in parking lot, stopped
    s->b: GO
    s<-b: GOING
    s<->b: Under gantry 1...
    s<->b: Under gantry 2...
    s<->b: Under gantry 3...
    s<->b: Under gantry 1...
    s<->b: Under gantry 2...
    s->b: PARK
    s<-b: PARKED
@enduml
