@startuml
title Under a gantry
participant Buggy as b #4f4
participant Station as s #44f
...
group Under gantry n
    s<-b: GANTRYn
    s->b: STOP
    s<-b: STOPPED
    note over s #fff: Wait 1 sec
    s->b: GO
    s<-b: GOING
end
...
@enduml
